todo/urls.py
from django.urls import path

from todo.views import (
    complete_task,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path(
        "task-create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task-update/<int:pk>/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task-delete/<int:pk>/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "complete-task/<int:pk>/",
        complete_task,
        name="complete-task"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    )
]

app_name = "todo"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("__debug__/", include("debug_toolbar.urls")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    date_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()
    mark_task = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["mark_task", "-date_time"]

    def __str__(self):
        return f"{self.content[:20]}..."

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Tag, Task


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    template_name = "todo/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = ["content", "tags"]
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


def complete_task(request, pk):
    task = Task.objects.get(id=pk)

    if task.mark_task:
        task.mark_task = False
    else:
        task.mark_task = True

    task.save()

    return HttpResponseRedirect(reverse_lazy("todo:index"))


templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Blog</title>{% endblock %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">

  <div class="row">

    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>

    <div class="col-sm-10">
      {% block content %}{% endblock %}
    </div>

  </div>

</div>

</body>
</html>

templates/includes/sidebar.html
<a href="{% url "todo:index" %}">Home</a>
<hr>
<a href="{% url 'todo:tag-list' %}">Tags</a>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Tasks List
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
        Add Task
    </a>
  </h1>
  {% if task_list %}
    <ul style="list-style: none">
      {% for task in task_list %}
        <li>
          <h4>{{ task.content }}
            {% if task.mark_task %}
              <span style="color: green;">Done <a href="{% url 'todo:complete-task' pk=task.id%}" class="btn btn-secondary link-to-page">Undo</a></span>
            {% else %}
              <span style="color: red;">Not Done <a href="{% url 'todo:complete-task' pk=task.id%}" class="btn btn-success link-to-page">Complete</a></span>
            {% endif %}
          </h4>
          <p>Created: {{ task.date_time }}
            {% if not task.mark_task %}
              <span style="color: #b01005;">Deadline: {{ task.deadline }}</span>
            {% endif %}
          </p>
          <p style="color: gray">Tags: {% for tag in task.tags.all %}
            {{ tag }}
          {% endfor %}</p>
          <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
          <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
        </li>
        <br>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tag List
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
        Add Tag
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list%}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
              <a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}